[[libstl]]
arch = "aarch64"
git-tree-sha1 = "3fcd8b21c9a340a5b8045f17001a2ff938f61777"
libgfortran_version = "5.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "39b50ea0de3895057c871d93dee0afa653704b3914af38e83ed2615961ff5994"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.2+0/libstl.v0.0.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "3185eceb85e7ff85df6ec3b9c7ea31320378b4d6"
libgfortran_version = "3.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "43adfe83a271b23808eadc609e47d046d3613a901b564560d3d2ec9b309cf136"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.2+0/libstl.v0.0.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "19a4e33778893a45cb10c0b7f322be2d05d542e2"
libgfortran_version = "4.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "2366929e336b1dbd59e5b009998565d35142aea3951ce7e109c6d73a1dd038aa"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.2+0/libstl.v0.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "3a902e44458974692b49a52c48998766d07c6013"
libgfortran_version = "5.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "b281809c03f0f56ebb82986e88d282533a13db1d345114b49f66c5de3264dfcb"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.2+0/libstl.v0.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
