[[libstl]]
arch = "aarch64"
git-tree-sha1 = "f45986b219d330f93617c45f47561ad99483a9ea"
libgfortran_version = "5.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "a82c26f660589a270f858faf3cdb96ae00c8173fbafb0ffe173c7bdc48dc1199"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.1+0/libstl.v0.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "1d2e46917d40e3aa7b62090006b78037865a5ff3"
libgfortran_version = "3.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "e805a6c47833bdf706819005b481834a4549e02b39563a14e47b29a5d2d45879"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.1+0/libstl.v0.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "a7a85029ee04000258f0abd17c81e882fc1a2c9a"
libgfortran_version = "4.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "5d17fb285c1a7784ed3035958d2f3ca1720e97c65bcb8453972d912691d28f0c"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.1+0/libstl.v0.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[libstl]]
arch = "x86_64"
git-tree-sha1 = "02f5abca5d63e5ec45a64f6aaf316251585dac56"
libgfortran_version = "5.0.0"
os = "macos"

    [[libstl.download]]
    sha256 = "12198a717654967d5de30282268272ea13048f98556891cfab2148008c9a5269"
    url = "https://github.com/AngelPone/Libstl_jll.jl/releases/download/libstl-v0.0.1+0/libstl.v0.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
