# Autogenerated wrapper script for libstl_jll for x86_64-apple-darwin-libgfortran4
export libstl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libstl")
JLLWrappers.@declare_library_product(libstl, "@rpath/libstl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libstl,
        "lib/libstl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
